### ISSUE TITLE
symbiosis-httpd-logger.go does not set ownership and permissions on default log file

### ISSUE THREAD

**Issue by banburybill** [BytemarkHosting/symbiosis#11]
When logging to the default log file, symbiosis-httpd-logger.go does not set ownership and permissions on the log file. Which therefore appears owned by root and with permissions 0600.

With websites where symbiosis-httpd-configure has generated specific configuration files, these log via default log files. So in this case, the log files, being owned by root, can't be manipulated by symbiosis-httpd-rotate-logs once it has dropped privs.

**Comment by patch0** [comment]
The permissions for the default log file are pulled from the parent directory (as they are for the per-domain log files).  This is all handled in the writeLog() function.  If the parent directory is owned by root, then the files get owned by root too (though maybe it should refuse to do this?).

The `symbiosis-httpd-rotate-logs` does not handle logs in `/var/log/apache2`, which are owned by `root:adm`.  These are handled by the default logrotate script in `/etc/logrotate.d/apache2`.

**Comment by banburybill** [comment]
writeLog() function()? I don't see it. And apologies, I think I messed up the terminology. I'm talking about what the code referes to as the default file, not a generated log name.

What I see is:

		if handles[default_file] == nil {
			handles[default_file] = safeOpen(default_file)
		}

followed immediately by:

		if handles[default_file] != nil {
			handles[default_file].WriteString(log + "\n")
		}

This is before the RE match that extracts the hostname, so there is no possibility of having a parent directory available.

**Comment by patch0** [comment]
Sorry, it appears the sync from our source to github is out of date.  I've now pushed some changes from November to github.  This particular issue is fixed in that push, and should no longer manifest itself.  

There was quite a bit of refactoring, so the logfile is only opened when it is written to, and the file opening is handled by the same function for both the default and per-domain log files, in this mysterious `writeLog()` function I mentioned before.

Your commits now have merge conflicts, but I will fix them up.

Thank you very much for spending time fixing this!

**Comment by patch0** [comment]
Closed by 39edd44
