### ISSUE TITLE
symbiosis-email-encrypt-passwords --verbose command is not recognised

### ISSUE THREAD

**Issue by joolsr** [BytemarkHosting/symbiosis#65]
Using Symbiosis Wheezy.

I need to encrypt a users email account password. Although I remember the password file for a user usually is updated with an encrypted version of same password this doesnt appear to be working for me at the moment.

I tried the below command from /srv as admin user

symbiosis-email-encrypt-passwords --verbose

but just get 

-bash: symbiosis-email: command not found

**Comment by joolsr** [comment]
Just spoke to Bytemark Support and for this command you need to prefix with 'sudo'. Then it worked fine for me.

So just take this as a note to add 'sudo' to the docs for this command ;-)

**Comment by patch0** [comment]
The `sudo` requirement is because of the path.  It was not anticipated that users would want to run `symbiosis-email-encrypt-passwords` by hand, as it is run on a cron (although one of the crontab entries is wrong #72) 

Without sudo, you can run `/usr/sbin/symbiosis-email-encrypt-passwords --verbose` and that should do the trick.
